<?php

namespace ContainerI9wKaJk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJew1pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t_jew1p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t_jew1p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClassroomController::Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClassroomController::delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClassroomController::list' => ['privates', '.service_locator.iTU.6EW', 'get_ServiceLocator_ITU_6EWService', true],
            'App\\Controller\\ClassroomController::toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController::Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController::delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController::list' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\ClubController::toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController::Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController::delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController::list' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\StudentController::toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ClassroomController:Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClassroomController:delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClassroomController:list' => ['privates', '.service_locator.iTU.6EW', 'get_ServiceLocator_ITU_6EWService', true],
            'App\\Controller\\ClassroomController:toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController:Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController:delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\ClubController:list' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\ClubController:toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController:Ajout' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController:delete' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'App\\Controller\\StudentController:list' => ['privates', '.service_locator.X75U880', 'get_ServiceLocator_X75U880Service', true],
            'App\\Controller\\StudentController:toedit' => ['privates', '.service_locator.KHii2Lq', 'get_ServiceLocator_KHii2LqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ClassroomController::Ajout' => '?',
            'App\\Controller\\ClassroomController::delete' => '?',
            'App\\Controller\\ClassroomController::list' => '?',
            'App\\Controller\\ClassroomController::toedit' => '?',
            'App\\Controller\\ClubController::Ajout' => '?',
            'App\\Controller\\ClubController::delete' => '?',
            'App\\Controller\\ClubController::list' => '?',
            'App\\Controller\\ClubController::toedit' => '?',
            'App\\Controller\\StudentController::Ajout' => '?',
            'App\\Controller\\StudentController::delete' => '?',
            'App\\Controller\\StudentController::list' => '?',
            'App\\Controller\\StudentController::toedit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClassroomController:Ajout' => '?',
            'App\\Controller\\ClassroomController:delete' => '?',
            'App\\Controller\\ClassroomController:list' => '?',
            'App\\Controller\\ClassroomController:toedit' => '?',
            'App\\Controller\\ClubController:Ajout' => '?',
            'App\\Controller\\ClubController:delete' => '?',
            'App\\Controller\\ClubController:list' => '?',
            'App\\Controller\\ClubController:toedit' => '?',
            'App\\Controller\\StudentController:Ajout' => '?',
            'App\\Controller\\StudentController:delete' => '?',
            'App\\Controller\\StudentController:list' => '?',
            'App\\Controller\\StudentController:toedit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
